source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'PodSubspecDependencyIssue_Example', :exclusive => true do
  pod "PodSubspecDependencyIssue", :path => "../"
end

target 'PodSubspecDependencyIssue_Tests', :exclusive => true do
  pod "PodSubspecDependencyIssue", :path => "../"

  
end
